# Generated by Django 4.2.7 on 2025-06-26 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationLoanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offered_interest_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "offered_loan_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "รอการตรวจสอบ"),
                            ("approved", "อนุมัติ"),
                            ("rejected", "ปฏิเสธ"),
                            ("waiting_docs", "รอเอกสาร"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("bank_notes", models.TextField(blank=True)),
                ("submitted_date", models.DateTimeField(auto_now_add=True)),
                ("response_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="bank_logos/"),
                ),
                ("contact_phone", models.CharField(max_length=20)),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LoanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("home", "สินเชื่อบ้าน"),
                            ("refinance", "รีไฟแนนซ์"),
                            ("equity", "สินเชื่อหลักประกัน"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_interest_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "max_interest_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "min_loan_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "max_loan_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("max_loan_term", models.IntegerField()),
                ("processing_fee", models.DecimalField(decimal_places=2, max_digits=5)),
                ("requirements", models.TextField()),
                ("features", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="refinance.bank"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("house", "บ้านเดี่ยว"),
                            ("townhouse", "ทาวน์เฮาส์"),
                            ("condo", "คอนโดมิเนียม"),
                            ("commercial", "อาคารพาณิชย์"),
                            ("land", "ที่ดิน"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                (
                    "land_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "building_size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "current_loan_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "property_documents",
                    models.FileField(blank=True, null=True, upload_to="property_docs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_bank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="refinance.bank",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefinanceApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "desired_loan_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("loan_term", models.IntegerField()),
                ("purpose", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "ร่าง"),
                            ("submitted", "ยื่นแล้ว"),
                            ("under_review", "ตรวจสอบ"),
                            ("approved", "อนุมัติ"),
                            ("rejected", "ปฏิเสธ"),
                            ("cancelled", "ยกเลิก"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("application_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan_products",
                    models.ManyToManyField(
                        through="refinance.ApplicationLoanProduct",
                        to="refinance.loanproduct",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="refinance.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_card", "บัตรประชาชน"),
                            ("house_registration", "ทะเบียนบ้าน"),
                            ("income_cert", "หนังสือรับรองเงินเดือน"),
                            ("bank_statement", "สเตทเมนต์ธนาคาร"),
                            ("property_deed", "โฉนดที่ดิน"),
                            ("building_permit", "ใบอนุญาตก่อสร้าง"),
                            ("other", "อื่นๆ"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("description", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="refinance.refinanceapplication",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="applicationloanproduct",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="refinance.refinanceapplication",
            ),
        ),
        migrations.AddField(
            model_name="applicationloanproduct",
            name="loan_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="refinance.loanproduct"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="applicationloanproduct",
            unique_together={("application", "loan_product")},
        ),
    ]
