# Generated by Django 4.2.7 on 2025-06-29 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("refinance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "promotion_type",
                    models.CharField(
                        choices=[
                            ("special_rate", "ดอกเบี้ยพิเศษ"),
                            ("cashback", "เงินคืน"),
                            ("no_fee", "ยกเว้นค่าธรรมเนียม"),
                            ("insurance", "ประกันฟรี"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "min_loan_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "max_loan_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "special_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "cashback_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_sponsored", models.BooleanField(default=False)),
                ("priority", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="promotions/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="refinance.bank"
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "เข้าสู่ระบบ"),
                            ("logout", "ออกจากระบบ"),
                            ("register", "สมัครสมาชิก"),
                            ("profile_update", "อัปเดตโปรไฟล์"),
                            ("property_add", "เพิ่มทรัพย์สิน"),
                            ("property_edit", "แก้ไขทรัพย์สิน"),
                            ("loan_comparison", "เปรียบเทียบสินเชื่อ"),
                            ("application_create", "ยื่นคำขอ"),
                            ("application_view", "ดูรายละเอียดคำขอ"),
                            ("document_upload", "อัปโหลดเอกสาร"),
                            ("page_view", "ดูหน้าเว็บ"),
                            ("search", "ค้นหา"),
                            ("admin_action", "การดำเนินการของแอดมิน"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("session_key", models.CharField(blank=True, max_length=50)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="refinance.refinanceapplication",
                    ),
                ),
                (
                    "related_property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="refinance.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
