# Generated by Django 4.2.7 on 2025-06-29 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("refinance", "0002_province_promotion_activitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่ออาชีพ")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("employee", "พนักงาน"),
                            ("business_owner", "เจ้าของกิจการ"),
                            ("freelance", "อิสระ"),
                            ("special_profession", "อาชีพพิเศษ"),
                            ("government", "ราชการ"),
                            ("military_police", "ทหาร/ตำรวจ"),
                        ],
                        max_length=50,
                        verbose_name="หมวดหมู่",
                    ),
                ),
                (
                    "loan_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="ตัวคูณรายได้สำหรับคำนวณวงเงินกู้",
                        max_digits=3,
                        verbose_name="ตัวคูณสินเชื่อ",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="ลำดับการแสดง"),
                ),
            ],
            options={
                "verbose_name": "อาชีพ",
                "verbose_name_plural": "อาชีพ",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ชื่อประเภท")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="รหัส"),
                ),
                ("description", models.TextField(blank=True, verbose_name="คำอธิบาย")),
                (
                    "max_ltv_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=85.0,
                        max_digits=5,
                        verbose_name="อัตราส่วน LTV สูงสุด (%)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="ลำดับการแสดง"),
                ),
            ],
            options={
                "verbose_name": "ประเภททรัพย์สิน",
                "verbose_name_plural": "ประเภททรัพย์สิน",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="activitylog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "บันทึกกิจกรรม",
                "verbose_name_plural": "บันทึกกิจกรรม",
            },
        ),
        migrations.AlterModelOptions(
            name="applicationloanproduct",
            options={
                "verbose_name": "สถานะคำขอต่อธนาคาร",
                "verbose_name_plural": "สถานะคำขอต่อธนาคาร",
            },
        ),
        migrations.AlterModelOptions(
            name="bank",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "ธนาคาร",
                "verbose_name_plural": "ธนาคาร",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={"verbose_name": "เอกสาร", "verbose_name_plural": "เอกสาร"},
        ),
        migrations.AlterModelOptions(
            name="loanproduct",
            options={
                "ordering": ["-is_featured", "display_order", "min_interest_rate"],
                "verbose_name": "ผลิตภัณฑ์สินเชื่อ",
                "verbose_name_plural": "ผลิตภัณฑ์สินเชื่อ",
            },
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={
                "ordering": ["-priority", "-is_sponsored", "-created_at"],
                "verbose_name": "โปรโมชั่น",
                "verbose_name_plural": "โปรโมชั่น",
            },
        ),
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name": "ทรัพย์สิน", "verbose_name_plural": "ทรัพย์สิน"},
        ),
        migrations.AlterModelOptions(
            name="province",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "จังหวัด",
                "verbose_name_plural": "จังหวัด",
            },
        ),
        migrations.AlterModelOptions(
            name="refinanceapplication",
            options={
                "ordering": ["-application_date"],
                "verbose_name": "คำขอรีไฟแนนซ์",
                "verbose_name_plural": "คำขอรีไฟแนนซ์",
            },
        ),
        migrations.AddField(
            model_name="bank",
            name="bank_type",
            field=models.CharField(
                choices=[
                    ("commercial", "ธนาคารพาณิชย์"),
                    ("government", "ธนาคารรัฐบาล"),
                    ("specialized", "ธนาคารเฉพาะกิจ"),
                ],
                default="commercial",
                max_length=20,
                verbose_name="ประเภทธนาคาร",
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="display_order",
            field=models.IntegerField(default=0, verbose_name="ลำดับการแสดง"),
        ),
        migrations.AddField(
            model_name="document",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="ตรวจสอบแล้ว"),
        ),
        migrations.AddField(
            model_name="document",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ตรวจสอบโดย",
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="display_order",
            field=models.IntegerField(default=0, verbose_name="ลำดับการแสดง"),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="documents_required",
            field=models.TextField(default={}, verbose_name="เอกสารที่ต้องใช้"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="แนะนำ"),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="max_age",
            field=models.IntegerField(default=65, verbose_name="อายุสูงสุด"),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="max_ltv_ratio",
            field=models.DecimalField(
                decimal_places=2,
                default=85.0,
                max_digits=5,
                verbose_name="LTV สูงสุด (%)",
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="min_income",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="รายได้ขั้นต่ำ"
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="promotion",
            name="cashback_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="เปอร์เซ็นต์เงินคืน (%)",
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="special_rate_period",
            field=models.IntegerField(
                default=12, verbose_name="ระยะเวลาดอกเบี้ยพิเศษ (เดือน)"
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="target_audience",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="กลุ่มเป้าหมาย"
            ),
        ),
        migrations.AddField(
            model_name="promotion",
            name="terms_and_conditions",
            field=models.TextField(blank=True, verbose_name="ข้อกำหนดและเงื่อนไข"),
        ),
        migrations.AddField(
            model_name="property",
            name="province",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="refinance.province",
                verbose_name="จังหวัด",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="province",
            name="display_order",
            field=models.IntegerField(default=0, verbose_name="ลำดับการแสดง"),
        ),
        migrations.AddField(
            model_name="province",
            name="region",
            field=models.CharField(
                choices=[
                    ("north", "ภาคเหนือ"),
                    ("northeast", "ภาคอีสาน"),
                    ("central", "ภาคกลาง"),
                    ("south", "ภาคใต้"),
                    ("east", "ภาคตะวันออก"),
                    ("west", "ภาคตะวันตก"),
                ],
                default=1,
                max_length=50,
                verbose_name="ภูมิภาค",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="refinanceapplication",
            name="monthly_income",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="รายได้ต่อเดือน",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("login", "เข้าสู่ระบบ"),
                    ("logout", "ออกจากระบบ"),
                    ("register", "สมัครสมาชิก"),
                    ("profile_update", "อัปเดตโปรไฟล์"),
                    ("property_add", "เพิ่มทรัพย์สิน"),
                    ("property_edit", "แก้ไขทรัพย์สิน"),
                    ("loan_comparison", "เปรียบเทียบสินเชื่อ"),
                    ("application_create", "ยื่นคำขอ"),
                    ("application_view", "ดูรายละเอียดคำขอ"),
                    ("document_upload", "อัปโหลดเอกสาร"),
                    ("page_view", "ดูหน้าเว็บ"),
                    ("search", "ค้นหา"),
                    ("admin_action", "การดำเนินการของแอดมิน"),
                ],
                max_length=20,
                verbose_name="ประเภทกิจกรรม",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="วันที่"),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="description",
            field=models.TextField(verbose_name="รายละเอียด"),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="extra_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="ข้อมูลเพิ่มเติม"
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP Address"
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="related_application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="refinance.refinanceapplication",
                verbose_name="คำขอที่เกี่ยวข้อง",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="related_property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="refinance.property",
                verbose_name="ทรัพย์สินที่เกี่ยวข้อง",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="session_key",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Session Key"
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้ใช้",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user_agent",
            field=models.TextField(blank=True, verbose_name="User Agent"),
        ),
        migrations.AlterField(
            model_name="applicationloanproduct",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="refinance.refinanceapplication",
                verbose_name="คำขอ",
            ),
        ),
        migrations.AlterField(
            model_name="applicationloanproduct",
            name="bank_notes",
            field=models.TextField(blank=True, verbose_name="หมายเหตุจากธนาคาร"),
        ),
        migrations.AlterField(
            model_name="applicationloanproduct",
            name="loan_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="refinance.loanproduct",
                verbose_name="ผลิตภัณฑ์สินเชื่อ",
            ),
        ),
        migrations.AlterField(
            model_name="applicationloanproduct",
            name="offered_interest_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="อัตราดอกเบี้ยที่เสนอ (%)",
            ),
        ),
        migrations.AlterField(
            model_name="applicationloanproduct",
            name="offered_loan_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="วงเงินที่อนุมัติ",
            ),
        ),
        migrations.AlterField(
            model_name="applicationloanproduct",
            name="response_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="วันที่ธนาคารตอบกลับ"
            ),
        ),
        migrations.AlterField(
            model_name="applicationloanproduct",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอการตรวจสอบ"),
                    ("approved", "อนุมัติ"),
                    ("rejected", "ปฏิเสธ"),
                    ("waiting_docs", "รอเอกสาร"),
                    ("cancelled", "ยกเลิก"),
                ],
                default="pending",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
        migrations.AlterField(
            model_name="applicationloanproduct",
            name="submitted_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="วันที่ส่งให้ธนาคาร"
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="code",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="รหัสธนาคาร"
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="contact_phone",
            field=models.CharField(max_length=20, verbose_name="เบอร์โทรติดต่อ"),
        ),
        migrations.AlterField(
            model_name="bank",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="ใช้งาน"),
        ),
        migrations.AlterField(
            model_name="bank",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="bank_logos/", verbose_name="โลโก้"
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="name",
            field=models.CharField(max_length=100, verbose_name="ชื่อธนาคาร"),
        ),
        migrations.AlterField(
            model_name="bank",
            name="website",
            field=models.URLField(blank=True, verbose_name="เว็บไซต์"),
        ),
        migrations.AlterField(
            model_name="document",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="refinance.refinanceapplication",
                verbose_name="คำขอ",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="description",
            field=models.CharField(blank=True, max_length=200, verbose_name="คำอธิบาย"),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("id_card", "บัตรประชาชน"),
                    ("house_registration", "ทะเบียนบ้าน"),
                    ("income_cert", "หนังสือรับรองเงินเดือน"),
                    ("salary_slip", "สลิปเงินเดือน"),
                    ("bank_statement", "สเตทเมนต์ธนาคาร"),
                    ("property_deed", "โฉนดที่ดิน"),
                    ("building_permit", "ใบอนุญาตก่อสร้าง"),
                    ("loan_statement", "สเตทเมนต์สินเชื่อปัจจุบัน"),
                    ("other", "อื่นๆ"),
                ],
                max_length=20,
                verbose_name="ประเภทเอกสาร",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="documents/", verbose_name="ไฟล์เอกสาร"),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="วันที่อัปโหลด"),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="refinance.bank",
                verbose_name="ธนาคาร",
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="features",
            field=models.TextField(verbose_name="จุดเด่น/คุณสมบัติ"),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="ใช้งาน"),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="loan_type",
            field=models.CharField(
                choices=[
                    ("home", "สินเชื่อบ้าน"),
                    ("refinance", "รีไฟแนนซ์"),
                    ("equity", "สินเชื่อหลักประกัน"),
                ],
                max_length=20,
                verbose_name="ประเภทสินเชื่อ",
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="max_interest_rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="อัตราดอกเบี้ยสูงสุด (%)"
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="max_loan_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="วงเงินกู้สูงสุด"
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="max_loan_term",
            field=models.IntegerField(verbose_name="ระยะเวลากู้สูงสุด (ปี)"),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="min_interest_rate",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="อัตราดอกเบี้ยต่ำสุด (%)"
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="min_loan_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="วงเงินกู้ขั้นต่ำ"
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="name",
            field=models.CharField(max_length=200, verbose_name="ชื่อผลิตภัณฑ์"),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="processing_fee",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="ค่าธรรมเนียม (%)"
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="requirements",
            field=models.TextField(verbose_name="เงื่อนไขและข้อกำหนด"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="refinance.bank",
                verbose_name="ธนาคาร",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="cashback_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="จำนวนเงินคืน",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="description",
            field=models.TextField(verbose_name="รายละเอียด"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="end_date",
            field=models.DateField(verbose_name="วันสิ้นสุดโปรโมชั่น"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="promotions/", verbose_name="รูปภาพ"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="ใช้งาน"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="is_sponsored",
            field=models.BooleanField(default=False, verbose_name="โฆษณา (Sponsored)"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="max_loan_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="วงเงินกู้สูงสุด",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="min_loan_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="วงเงินกู้ขั้นต่ำ"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="priority",
            field=models.IntegerField(default=0, verbose_name="ลำดับความสำคัญ"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="promotion_type",
            field=models.CharField(
                choices=[
                    ("special_rate", "ดอกเบี้ยพิเศษ"),
                    ("cashback", "เงินคืน"),
                    ("no_fee", "ยกเว้นค่าธรรมเนียม"),
                    ("insurance", "ประกันฟรี"),
                    ("combo", "แพ็กเกจรวม"),
                ],
                max_length=20,
                verbose_name="ประเภทโปรโมชั่น",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="special_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="อัตราดอกเบี้ยพิเศษ (%)",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="start_date",
            field=models.DateField(verbose_name="วันเริ่มโปรโมชั่น"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="title",
            field=models.CharField(max_length=200, verbose_name="หัวข้อโปรโมชั่น"),
        ),
        migrations.AlterField(
            model_name="property",
            name="address",
            field=models.TextField(verbose_name="ที่อยู่"),
        ),
        migrations.AlterField(
            model_name="property",
            name="building_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="ขนาดอาคาร (ตร.ม.)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="current_bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="refinance.bank",
                verbose_name="ธนาคารปัจจุบัน",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="current_loan_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="ยอดหนี้คงเหลือ",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="estimated_value",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="มูลค่าประเมิน"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="land_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="ขนาดที่ดิน (ตร.ว.)",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="เจ้าของ",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_documents",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="property_docs/",
                verbose_name="เอกสารทรัพย์สิน",
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="ใช้งาน"),
        ),
        migrations.AlterField(
            model_name="province",
            name="name",
            field=models.CharField(max_length=100, verbose_name="ชื่อจังหวัด"),
        ),
        migrations.AlterField(
            model_name="province",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ชื่อภาษาอังกฤษ"
            ),
        ),
        migrations.AlterField(
            model_name="refinanceapplication",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้สมัคร",
            ),
        ),
        migrations.AlterField(
            model_name="refinanceapplication",
            name="application_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="วันที่ยื่น"),
        ),
        migrations.AlterField(
            model_name="refinanceapplication",
            name="desired_loan_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="จำนวนเงินกู้ที่ต้องการ"
            ),
        ),
        migrations.AlterField(
            model_name="refinanceapplication",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="อัปเดตล่าสุด"),
        ),
        migrations.AlterField(
            model_name="refinanceapplication",
            name="loan_products",
            field=models.ManyToManyField(
                through="refinance.ApplicationLoanProduct",
                to="refinance.loanproduct",
                verbose_name="ผลิตภัณฑ์สินเชื่อ",
            ),
        ),
        migrations.AlterField(
            model_name="refinanceapplication",
            name="loan_term",
            field=models.IntegerField(verbose_name="ระยะเวลากู้ (ปี)"),
        ),
        migrations.AlterField(
            model_name="refinanceapplication",
            name="notes",
            field=models.TextField(blank=True, verbose_name="หมายเหตุ"),
        ),
        migrations.AlterField(
            model_name="refinanceapplication",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="refinance.property",
                verbose_name="ทรัพย์สิน",
            ),
        ),
        migrations.AlterField(
            model_name="refinanceapplication",
            name="purpose",
            field=models.TextField(verbose_name="วัตถุประสงค์"),
        ),
        migrations.AlterField(
            model_name="refinanceapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "ร่าง"),
                    ("submitted", "ยื่นแล้ว"),
                    ("document_review", "ตรวจสอบเอกสาร"),
                    ("under_review", "พิจารณา"),
                    ("approved", "อนุมัติ"),
                    ("contract_signing", "ทำสัญญา"),
                    ("completed", "เสร็จสิ้น"),
                    ("rejected", "ปฏิเสธ"),
                    ("cancelled", "ยกเลิก"),
                ],
                default="draft",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
        migrations.AddField(
            model_name="refinanceapplication",
            name="occupation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="refinance.occupation",
                verbose_name="อาชีพ",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="refinance.propertytype",
                verbose_name="ประเภททรัพย์สิน",
            ),
        ),
    ]
