# Generated by Django 4.2.7 on 2025-06-29 15:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "refinance",
            "0003_occupation_propertytype_alter_activitylog_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "ร้าง"),
                            ("submitted", "ยื่นแล้ว"),
                            ("under_review", "กำลังพิจารณา"),
                            ("approved", "อนุมัติ"),
                            ("rejected", "ปฏิเสธ"),
                            ("cancelled", "ยกเลิก"),
                        ],
                        default="submitted",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "offered_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="อัตราดอกเบี้ยที่เสนอ (%)",
                    ),
                ),
                (
                    "offered_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="วงเงินที่อนุมัติ (บาท)",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่ยื่น"),
                ),
                (
                    "response_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่ตอบกลับ"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
            ],
            options={
                "verbose_name": "การยื่นสมัครต่อธนาคาร",
                "verbose_name_plural": "การยื่นสมัครต่อธนาคาร",
            },
        ),
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="จำนวน"
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="จำนวนขั้นต่ำ (บาท)",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="จำนวนสูงสุด (บาท)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
            ],
            options={
                "verbose_name": "ค่าธรรมเนียม",
                "verbose_name_plural": "ค่าธรรมเนียม",
            },
        ),
        migrations.CreateModel(
            name="FeeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="ชื่อค่าธรรมเนียม"),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="รหัส"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="รายละเอียด"),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[("percentage", "เปอร์เซ็นต์"), ("fixed", "ค่าคงที่")],
                        max_length=20,
                        verbose_name="ประเภทค่าธรรมเนียม",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ใช้งาน")),
            ],
            options={
                "verbose_name": "ประเภทค่าธรรมเนียม",
                "verbose_name_plural": "ประเภทค่าธรรมเนียม",
            },
        ),
        migrations.CreateModel(
            name="InterestRateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="อัตราดอกเบี้ย (%)"
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="วันที่มีผล")),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="หมายเหตุ"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="วันที่บันทึก"
                    ),
                ),
            ],
            options={
                "verbose_name": "ประวัติอัตราดอกเบี้ย",
                "verbose_name_plural": "ประวัติอัตราดอกเบี้ย",
                "ordering": ["-effective_date", "bank__name"],
            },
        ),
        migrations.CreateModel(
            name="LoanApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_no",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="เลขที่ใบสมัคร"
                    ),
                ),
                (
                    "loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="จำนวนเงินกู้ (บาท)",
                    ),
                ),
                ("loan_term", models.IntegerField(verbose_name="ระยะเวลากู้ (ปี)")),
                (
                    "purpose",
                    models.CharField(
                        default="refinance", max_length=100, verbose_name="วัตถุประสงค์"
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="รายได้ต่อเดือน (บาท)",
                    ),
                ),
                (
                    "monthly_expense",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="รายจ่ายต่อเดือน (บาท)",
                    ),
                ),
                (
                    "other_debts",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="หนี้สินอื่น (บาท)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "ร้าง"),
                            ("submitted", "ยื่นแล้ว"),
                            ("under_review", "กำลังพิจารณา"),
                            ("approved", "อนุมัติ"),
                            ("rejected", "ปฏิเสธ"),
                            ("cancelled", "ยกเลิก"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="สถานะ",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่ยื่น"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่พิจารณา"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="วันที่อนุมัติ"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="หมายเหตุ")),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="หมายเหตุแอดมิน"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
            ],
            options={
                "verbose_name": "ใบสมัครสินเชื่อ",
                "verbose_name_plural": "ใบสมัครสินเชื่อ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="คีย์"),
                ),
                ("value", models.TextField(verbose_name="ค่า")),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("text", "ข้อความ"),
                            ("number", "ตัวเลข"),
                            ("boolean", "เปิด/ปิด"),
                            ("json", "JSON"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="ประเภท",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="คำอธิบาย"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        default="general", max_length=50, verbose_name="หมวดหมู่"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="แสดงสาธารณะ"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
                ),
            ],
            options={
                "verbose_name": "การตั้งค่าระบบ",
                "verbose_name_plural": "การตั้งค่าระบบ",
                "ordering": ["category", "key"],
            },
        ),
        migrations.RemoveField(
            model_name="refinanceapplication",
            name="applicant",
        ),
        migrations.RemoveField(
            model_name="refinanceapplication",
            name="loan_products",
        ),
        migrations.RemoveField(
            model_name="refinanceapplication",
            name="occupation",
        ),
        migrations.RemoveField(
            model_name="refinanceapplication",
            name="property",
        ),
        migrations.AlterModelOptions(
            name="activitylog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "บันทึกการใช้งาน",
                "verbose_name_plural": "บันทึกการใช้งาน",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "เอกสาร",
                "verbose_name_plural": "เอกสาร",
            },
        ),
        migrations.AlterModelOptions(
            name="loanproduct",
            options={
                "ordering": ["bank__name", "display_order", "name"],
                "verbose_name": "ผลิตภัณฑ์สินเชื่อ",
                "verbose_name_plural": "ผลิตภัณฑ์สินเชื่อ",
            },
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={
                "ordering": ["-is_sponsored", "-priority", "-start_date"],
                "verbose_name": "โปรโมชั่น",
                "verbose_name_plural": "โปรโมชั่น",
            },
        ),
        migrations.AlterModelOptions(
            name="property",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ทรัพย์สิน",
                "verbose_name_plural": "ทรัพย์สิน",
            },
        ),
        migrations.RenameField(
            model_name="promotion",
            old_name="terms_and_conditions",
            new_name="terms_conditions",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="extra_data",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="related_application",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="related_property",
        ),
        migrations.RemoveField(
            model_name="activitylog",
            name="session_key",
        ),
        migrations.RemoveField(
            model_name="loanproduct",
            name="documents_required",
        ),
        migrations.RemoveField(
            model_name="loanproduct",
            name="features",
        ),
        migrations.RemoveField(
            model_name="loanproduct",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="loanproduct",
            name="loan_type",
        ),
        migrations.RemoveField(
            model_name="loanproduct",
            name="max_interest_rate",
        ),
        migrations.RemoveField(
            model_name="loanproduct",
            name="max_loan_term",
        ),
        migrations.RemoveField(
            model_name="loanproduct",
            name="max_ltv_ratio",
        ),
        migrations.RemoveField(
            model_name="loanproduct",
            name="min_interest_rate",
        ),
        migrations.RemoveField(
            model_name="loanproduct",
            name="requirements",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="cashback_amount",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="cashback_percentage",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="image",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="target_audience",
        ),
        migrations.RemoveField(
            model_name="property",
            name="current_bank",
        ),
        migrations.RemoveField(
            model_name="property",
            name="current_loan_balance",
        ),
        migrations.RemoveField(
            model_name="property",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="property",
            name="property_documents",
        ),
        migrations.AddField(
            model_name="activitylog",
            name="details",
            field=models.JSONField(
                blank=True, null=True, verbose_name="ข้อมูลเพิ่มเติม"
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="brand_color",
            field=models.CharField(
                default="#007bff",
                help_text="รหัสสี Hex เช่น #FF0000",
                max_length=7,
                verbose_name="สีแบรนด์",
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="อีเมลติดต่อ"
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="description",
            field=models.TextField(blank=True, verbose_name="รายละเอียด"),
        ),
        migrations.AddField(
            model_name="bank",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="แนะนำพิเศษ"),
        ),
        migrations.AddField(
            model_name="bank",
            name="marketing_message",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="ข้อความการตลาด"
            ),
        ),
        migrations.AddField(
            model_name="bank",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
        ),
        migrations.AddField(
            model_name="document",
            name="name",
            field=models.CharField(
                default=1, max_length=200, verbose_name="ชื่อเอกสาร"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="เจ้าของ",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="วันที่ตรวจสอบ"
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="appraisal_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="ค่าประเมินทรัพย์ (บาท)",
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="description",
            field=models.TextField(blank=True, verbose_name="รายละเอียด"),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="interest_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=5,
                verbose_name="อัตราดอกเบี้ย (%)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="interest_rate_type",
            field=models.CharField(
                choices=[
                    ("fixed", "อัตราคงที่"),
                    ("floating", "อัตราลอยตัว"),
                    ("mixed", "อัตราผสม"),
                ],
                default="floating",
                max_length=20,
                verbose_name="ประเภทอัตราดอกเบี้ย",
            ),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="is_popular",
            field=models.BooleanField(default=False, verbose_name="ยอดนิยม"),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="max_ltv",
            field=models.IntegerField(
                default=1,
                help_text="Loan to Value Ratio",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="LTV สูงสุด (%)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="max_term_years",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
                verbose_name="ระยะเวลากู้สูงสุด (ปี)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="min_age",
            field=models.IntegerField(default=20, verbose_name="อายุขั้นต่ำ (ปี)"),
        ),
        migrations.AddField(
            model_name="loanproduct",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("home_loan", "สินเชื่อบ้าน"),
                    ("refinance", "รีไฟแนนซ์"),
                    ("home_equity", "สินเชื่อเพื่อบ้าน"),
                    ("construction", "สินเชื่อก่อสร้าง"),
                ],
                default=1,
                max_length=20,
                verbose_name="ประเภทสินเชื่อ",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="promotion",
            name="banner_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="promotion_banners/",
                verbose_name="รูปป้ายโปรโมชั่น",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="existing_bank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="existing_loans",
                to="refinance.bank",
                verbose_name="ธนาคารปัจจุบัน",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="existing_loan_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="ยอดคงเหลือ (บาท)",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="has_existing_loan",
            field=models.BooleanField(default=False, verbose_name="มีสินเชื่ออยู่"),
        ),
        migrations.AddField(
            model_name="property",
            name="name",
            field=models.CharField(
                default=1, max_length=200, verbose_name="ชื่อทรัพย์สิน"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="รหัสไปรษณีย์"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="purchase_date",
            field=models.DateField(blank=True, null=True, verbose_name="วันที่ซื้อ"),
        ),
        migrations.AddField(
            model_name="property",
            name="purchase_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="ราคาซื้อ (บาท)",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
        ),
        migrations.AddField(
            model_name="property",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to=settings.AUTH_USER_MODEL,
                verbose_name="เจ้าของ",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("login", "เข้าสู่ระบบ"),
                    ("logout", "ออกจากระบบ"),
                    ("register", "สมัครสมาชิก"),
                    ("profile_update", "อัปเดตโปรไฟล์"),
                    ("property_add", "เพิ่มทรัพย์สิน"),
                    ("loan_comparison", "เปรียบเทียบสินเชื่อ"),
                    ("loan_application", "ยื่นใบสมัครสินเชื่อ"),
                    ("document_upload", "อัปโหลดเอกสาร"),
                    ("page_view", "เข้าดูหน้า"),
                    ("other", "อื่นๆ"),
                ],
                max_length=30,
                verbose_name="ประเภทกิจกรรม",
            ),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="description",
            field=models.CharField(max_length=500, verbose_name="รายละเอียด"),
        ),
        migrations.AlterField(
            model_name="activitylog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_logs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้ใช้",
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="bank_type",
            field=models.CharField(
                choices=[
                    ("government", "ธนาคารรัฐ"),
                    ("private", "ธนาคารเอกชน"),
                    ("foreign", "ธนาคารต่างประเทศ"),
                ],
                default="private",
                max_length=20,
                verbose_name="ประเภทธนาคาร",
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="เบอร์ติดต่อ"
            ),
        ),
        migrations.AlterField(
            model_name="bank",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
        ),
        migrations.AlterField(
            model_name="document",
            name="description",
            field=models.TextField(blank=True, verbose_name="รายละเอียด"),
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("id_card", "บัตรประชาชน"),
                    ("house_registration", "ทะเบียนบ้าน"),
                    ("income_statement", "หลักฐานรายได้"),
                    ("bank_statement", "สลิปเงินเดือน"),
                    ("property_document", "เอกสารสิทธิ์ทรัพย์สิน"),
                    ("appraisal_report", "รายงานการประเมิน"),
                    ("other", "อื่นๆ"),
                ],
                max_length=30,
                verbose_name="ประเภทเอกสาร",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="documents/", verbose_name="ไฟล์"),
        ),
        migrations.AlterField(
            model_name="document",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้ตรวจสอบ",
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_products",
                to="refinance.bank",
                verbose_name="ธนาคาร",
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="max_age",
            field=models.IntegerField(default=65, verbose_name="อายุสูงสุด (ปี)"),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="max_loan_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="วงเงินกู้สูงสุด (บาท)"
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="min_income",
            field=models.DecimalField(
                decimal_places=2,
                default=15000,
                max_digits=12,
                verbose_name="รายได้ขั้นต่ำ (บาท/เดือน)",
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="min_loan_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="วงเงินกู้ขั้นต่ำ (บาท)"
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="name",
            field=models.CharField(max_length=100, verbose_name="ชื่อผลิตภัณฑ์"),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="processing_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="ค่าธรรมเนียมจัดการ (%)",
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotions",
                to="refinance.bank",
                verbose_name="ธนาคาร",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="is_sponsored",
            field=models.BooleanField(default=False, verbose_name="โปรโมชั่นสปอนเซอร์"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="max_loan_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="วงเงินกู้สูงสุด (บาท)",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="min_loan_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="วงเงินกู้ขั้นต่ำ (บาท)",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="priority",
            field=models.IntegerField(
                default=0,
                help_text="เลขมากขึ้นจะแสดงก่อน",
                verbose_name="ลำดับความสำคัญ",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="promotion_type",
            field=models.CharField(
                choices=[
                    ("special_rate", "อัตราดอกเบี้ยพิเศษ"),
                    ("fee_waiver", "ยกเว้นค่าธรรมเนียม"),
                    ("cashback", "เงินคืน"),
                    ("gift", "ของแถม"),
                    ("other", "อื่นๆ"),
                ],
                max_length=20,
                verbose_name="ประเภทโปรโมชั่น",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="special_rate_period",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ระยะเวลาอัตราพิเศษ (เดือน)"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="title",
            field=models.CharField(max_length=200, verbose_name="ชื่อโปรโมชั่น"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="วันที่แก้ไข"),
        ),
        migrations.AlterField(
            model_name="property",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
        ),
        migrations.AlterField(
            model_name="property",
            name="estimated_value",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="มูลค่าประเมิน (บาท)"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("house", "บ้านเดี่ยว"),
                    ("townhouse", "ทาวน์เฮ้าส์"),
                    ("condo", "คอนโดมิเนียม"),
                    ("apartment", "อพาร์ทเมนต์"),
                    ("commercial", "อาคารพาณิชย์"),
                    ("land", "ที่ดิน"),
                ],
                max_length=20,
                verbose_name="ประเภท",
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ชื่อจังหวัด (อังกฤษ)"
            ),
        ),
        migrations.AlterField(
            model_name="province",
            name="region",
            field=models.CharField(
                choices=[
                    ("north", "ภาคเหนือ"),
                    ("northeast", "ภาคตะวันออกเฉียงเหนือ"),
                    ("central", "ภาคกลาง"),
                    ("east", "ภาคตะวันออก"),
                    ("west", "ภาคตะวันตก"),
                    ("south", "ภาคใต้"),
                ],
                max_length=20,
                verbose_name="ภาค",
            ),
        ),
        migrations.DeleteModel(
            name="ApplicationLoanProduct",
        ),
        migrations.DeleteModel(
            name="Occupation",
        ),
        migrations.DeleteModel(
            name="PropertyType",
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="refinance.property",
                verbose_name="ทรัพย์สิน",
            ),
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้สมัคร",
            ),
        ),
        migrations.AddField(
            model_name="interestratehistory",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_history",
                to="refinance.bank",
                verbose_name="ธนาคาร",
            ),
        ),
        migrations.AddField(
            model_name="interestratehistory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้บันทึก",
            ),
        ),
        migrations.AddField(
            model_name="interestratehistory",
            name="loan_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_history",
                to="refinance.loanproduct",
                verbose_name="ผลิตภัณฑ์สินเชื่อ",
            ),
        ),
        migrations.AddField(
            model_name="fee",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fees",
                to="refinance.bank",
                verbose_name="ธนาคาร",
            ),
        ),
        migrations.AddField(
            model_name="fee",
            name="fee_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="refinance.feetype",
                verbose_name="ประเภทค่าธรรมเนียม",
            ),
        ),
        migrations.AddField(
            model_name="applicationbank",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_banks",
                to="refinance.loanapplication",
                verbose_name="ใบสมัคร",
            ),
        ),
        migrations.AddField(
            model_name="applicationbank",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="refinance.bank",
                verbose_name="ธนาคาร",
            ),
        ),
        migrations.AddField(
            model_name="applicationbank",
            name="loan_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="refinance.loanproduct",
                verbose_name="ผลิตภัณฑ์สินเชื่อ",
            ),
        ),
        migrations.AddField(
            model_name="applicationbank",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="refinance.promotion",
                verbose_name="โปรโมชั่น",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="refinance.loanapplication",
                verbose_name="ใบสมัคร",
            ),
        ),
        migrations.DeleteModel(
            name="RefinanceApplication",
        ),
        migrations.AlterUniqueTogether(
            name="fee",
            unique_together={("bank", "fee_type")},
        ),
        migrations.AlterUniqueTogether(
            name="applicationbank",
            unique_together={("application", "bank")},
        ),
    ]
