# Generated by Django 4.2.7 on 2025-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refinance", "0004_applicationbank_fee_feetype_interestratehistory_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationbank",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "ร่าง"),
                    ("submitted", "ยื่นแล้ว"),
                    ("under_review", "กำลังพิจารณา"),
                    ("approved", "อนุมัติ"),
                    ("rejected", "ปฏิเสธ"),
                    ("cancelled", "ยกเลิก"),
                ],
                default="submitted",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
        migrations.AlterField(
            model_name="loanapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "ร่าง"),
                    ("submitted", "ยื่นแล้ว"),
                    ("under_review", "กำลังพิจารณา"),
                    ("approved", "อนุมัติ"),
                    ("rejected", "ปฏิเสธ"),
                    ("cancelled", "ยกเลิก"),
                ],
                default="draft",
                max_length=20,
                verbose_name="สถานะ",
            ),
        ),
    ]
