# Generated by Django 4.2.7 on 2025-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refinance", "0005_alter_applicationbank_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="หัวข้อ")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="รายละเอียด"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="advertisements/",
                        verbose_name="รูปภาพโฆษณา",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="ลิงก์ (URL)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="แสดงผล")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="วันที่สร้าง"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="แก้ไขล่าสุด"),
                ),
            ],
            options={
                "verbose_name": "โฆษณา/ข่าวสาร",
                "verbose_name_plural": "โฆษณาและข่าวสาร",
                "ordering": ["-created_at"],
            },
        ),
    ]
