# Generated by Django 4.2.7 on 2025-08-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refinance", "0006_advertisement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="province",
            name="region",
            field=models.CharField(
                choices=[
                    ("north", "ภาคเหนือ"),
                    ("northeast", "ภาคตะวันออกเฉียงเหนือ"),
                    ("central", "ภาคกลาง"),
                    ("east", "ภาคภาคตะวันออก"),
                    ("west", "ภาคตะวันตก"),
                    ("south", "ภาคใต้"),
                ],
                max_length=20,
                verbose_name="ภาค",
            ),
        ),
    ]
