# Generated by Django 4.2.7 on 2025-08-10 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("refinance", "0007_alter_province_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="ชื่อบทความ")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="คำอธิบายสั้นๆ เกี่ยวกับบทความ", verbose_name="บทสรุป"
                    ),
                ),
                ("content", models.TextField(verbose_name="เนื้อหาเต็ม")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="article_images/",
                        verbose_name="รูปภาพประกอบ",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="วันที่เผยแพร่"
                    ),
                ),
            ],
            options={
                "verbose_name": "บทความ",
                "verbose_name_plural": "บทความ",
                "ordering": ["-published_date"],
            },
        ),
    ]
