# Generated by Django 4.2.7 on 2025-08-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refinance", "0008_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanapplication",
            name="applied_bank_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
