# Generated by Django 4.2.7 on 2025-08-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("refinance", "0009_loanapplication_applied_bank_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationbank",
            name="contact_email_snapshot",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="อีเมลติดต่อ"
            ),
        ),
        migrations.AddField(
            model_name="applicationbank",
            name="contact_phone_snapshot",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="เบอร์โทรติดต่อ"
            ),
        ),
        migrations.AddField(
            model_name="applicationbank",
            name="interest_rate_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="อัตราดอกเบี้ย (%)",
            ),
        ),
        migrations.AddField(
            model_name="applicationbank",
            name="max_ltv_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="LTV สูงสุด (%)",
            ),
        ),
        migrations.AddField(
            model_name="applicationbank",
            name="max_term_years_snapshot",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ระยะเวลากู้สูงสุด (ปี)"
            ),
        ),
        migrations.AddField(
            model_name="applicationbank",
            name="processing_fee_percent_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="ค่าธรรมเนียม (%)",
            ),
        ),
        migrations.AddField(
            model_name="applicationbank",
            name="product_name_snapshot",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="ชื่อผลิตภัณฑ์ตอนยื่น",
            ),
        ),
        migrations.AddField(
            model_name="applicationbank",
            name="product_note_snapshot",
            field=models.TextField(
                blank=True, default="", verbose_name="หมายเหตุผลิตภัณฑ์"
            ),
        ),
    ]
