# Generated by Django 4.2.7 on 2025-06-26 10:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?1?\\d{9,15}$"
                            )
                        ],
                    ),
                ),
                ("citizen_id", models.CharField(max_length=13, unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.TextField()),
                (
                    "income_source",
                    models.CharField(
                        choices=[
                            ("salary", "เงินเดือน"),
                            ("business", "ธุรกิจส่วนตัว"),
                            ("freelance", "อิสระ/ฟรีแลนซ์"),
                            ("investment", "การลงทุน"),
                            ("other", "อื่นๆ"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "monthly_expenses",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
