# Generated by Django 4.2.7 on 2025-06-29 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="citizen_id",
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="income_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("salary", "เงินเดือน"),
                    ("business", "ธุรกิจส่วนตัว"),
                    ("freelance", "อิสระ/ฟรีแลนซ์"),
                    ("investment", "การลงทุน"),
                    ("other", "อื่นๆ"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="monthly_expenses",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="monthly_income",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^\\+?1?\\d{9,15}$")
                ],
            ),
        ),
    ]
