# Generated by Django 4.2.7 on 2025-07-03 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="รูปแบบเบอร์โทรศัพท์ไม่ถูกต้อง (อนุญาตเฉพาะตัวเลข 9-15 หลัก)",
                        regex="^[0-9]{9,15}$",
                    )
                ],
            ),
        ),
    ]
