# Generated by Django 4.2.7 on 2025-07-03 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0003_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["user__username"],
                "verbose_name": "โปรไฟล์ผู้ใช้",
                "verbose_name_plural": "โปรไฟล์ผู้ใช้",
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(max_length=50, verbose_name="ประเภทกิจกรรม"),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="คำอธิบายกิจกรรม"),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL ที่เข้าถึง",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="เวลา"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="User Agent"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="Session Key"
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="ข้อมูลเพิ่มเติม"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้งาน",
                    ),
                ),
            ],
            options={
                "verbose_name": "บันทึกการใช้งาน",
                "verbose_name_plural": "บันทึกการใช้งาน",
                "ordering": ["-timestamp"],
            },
        ),
    ]
