# Generated by Django 4.2.7 on 2025-08-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_userprofile_options_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="terms_accepted",
            field=models.BooleanField(
                default=False, verbose_name="ยอมรับข้อตกลงและเงื่อนไข"
            ),
        ),
    ]
