# Generated by Django 4.2.7 on 2025-08-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_terms_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'ผู้ใช้ทั่วไป'), ('bank', 'ธนาคาร')], default='user', max_length=20, verbose_name='สิทธิ์ผู้ใช้'),
        ),
    ]
